---
- name: Converge
  hosts: localhost
  collections:
    - dtms.dellemc_cisco_collection
  tasks:
    - include_vars: vars.yml
    - name: "Include deactivatezoneset"
      include_role:
        name: "deactivatezoneset"
