# Copyright Â© 2020 Dell Inc. or its subsidiaries. All Rights Reserved.
# This software is protected, without limitation, by copyright law and
# international treaties. Use of this software and the intellectual property
# contained therein is expressly limited to the terms and conditions of the
# License Agreement under which it is provided by or on behalf of Dell Inc
# or its subsidiaries.
# 
# Author: Nishu Prakash. [ nishu.prakash@dell.com ]
# File Created: 2020-07-30, 1:32:45 pm
# .........................................................................
# Modified By: Nishu Prakash. [ nishu.prakash@dell.com ]
# Last Modified: 2020-08-27, 6:12:47 pm 
# -------------------------------------------------------------------------

---
  - name: Prepare
    hosts: all
    collections:
      - dtms.dellemc_cisco_collection
    vars_files:
      - vars.yml
    tasks:
      - include_vars: vars.yml
      - name: Create Cisco Endpoint for test
        include_role:
          name: create_endpoint
        vars:
          endpoint: "{{ lookup('env','CISCO_MDS_ENDPOINT_NAME') }}"
          endpoint_host: "{{ lookup('env','CISCO_MDS_ENDPOINT_HOST') }}"
          endpoint_user: "{{ lookup('env','CISCO_MDS_USER') }}"
          endpoint_password: "{{ lookup('env','CISCO_MDS_PASSWORD') }}"
      
      